language: python
python:
  - "2.7"
before_install:
  - "svn checkout http://py-leveldb.googlecode.com/svn/trunk/ leveldb"
  - "./leveldb/compile_leveldb.sh"
  - "python leveldb/setup.py build"
  - "sudo python leveldb/setup.py install"
install:
  - "pip install . --use-mirrors"
script: nosetests
