language: python
python:
  - "2.7"
before_install:
  - "svn checkout http://py-leveldb.googlecode.com/svn/trunk/ py-leveldb-read-only"
  - "cd py-leveldb-read-only"
  - "./compile_leveldb.sh"
  - "python setup.py build"
  - "python setup.py install"
  - "cd .."
install:
  - "pip install . --use-mirrors"
script: nosetests
